#!/bin/bash

USERNAME='minecraft'
SERVICE='server.jar'
SCNAME='minecraft'
MC_PATH='/srv/minecraft/server'

XMX="1024M"
XMS="128M"
XMN="256M"
ADV="-XX:+UseConcMarkSweepGC -XX:+CMSIncrementalPacing -XX:ParallelGCThreads=4 -XX:+AggressiveOpts "

cd $MC_PATH

ME=`whoami`

if [ $ME == $USERNAME ] ; then
	if pgrep -u $USERNAME -f $SERVICE > /dev/null
	then
		echo "$SERVICE is already running!"
		exit 1
	else
		echo "Starting $SERVICE..."
		screen -AmdS $SCNAME java -Xmx$XMX -Xms$XMS -Xmn$XMN $ADV -jar $SERVICE nogui
	fi
else
	echo "Please run the minecraft user."
	exit 1
fi
